#!/bin/sh
bspc rule -r "*"

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

###---Autostart---###
xrdb ~/.Xresources &

###---MONITORS---###
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color "$color15"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color3"
bspc config presel_feedback_color "$color1"
bspc config urgent_border_color "#dd2727"

###---Monitor And Desktop Settings----###
bspc config top_padding 20
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10

###---Rules---###
SCREEN_WIDTH=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1)
SCREEN_HEIGHT=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2)
WIDTH=1000
HEIGHT=500
X_OFFSET=$(( ($SCREEN_WIDTH - $WIDTH) / 2))
Y_OFFSET=$(( ($SCREEN_HEIGHT - $HEIGHT) / 2))

bspc rule -a Library sticky=on state=floating rectangle="${WIDTH}x${HEIGHT}+${X_OFFSET}+${Y_OFFSET}"
bspc rule -a Gimp desktop=^5 follow=on state=floating
bspc rule -a mpv:mpvFloating sticky=on state=floating
bspc rule -a Zathura state=tiled
bspc rule -a firefox:Toolkit sticky=on state=floating

###---Programs---###
$HOME/.config/polybar/launch.sh
