#!/bin/zsh

LIBRARY_FILE="$HOME/dotfiles/scripts/rofi/library.txt"
LIBRARY_FOLDER="$HOME/Documents"

if ps -aux | grep "[L]ibrary" > /dev/null; then
    i3-msg 'scratchpad show'
else
    line=$(cat $LIBRARY_FILE | rofi -dmenu -i -p Library)
    result=$(echo "$line" | cut -f2 -d'-')

    if [ $result = "todo" ]; then
        st -c Library -e calcurse & disown
    elif [ $result = "calc" ]; then
        st -c Library -e python -ic "from math import *; import cmath" & disown
    elif [ $result = "arch" ]; then
        st -c Library -e ranger "/usr/share/doc/arch-wiki/html/en" & disown
    elif [ $result = "temp" ]; then
        st -c Library -e vim "/tmp/thinkering" & disown
    elif [ -z $result ]; then
        exit 0
    else
        result="${LIBRARY_FOLDER}/${result}"
        st -c Library -e vim $result & disown
    fi
fi
